"""Intent routing for the HR assistant.

The router decides only *how* a message is answered - it never produces
the answer itself. Every reply is generated by the LLM:

- CHAT   -> conversational reply via the LLM, WITHOUT document retrieval
- POLICY -> grounded RAG answer: (optional query condensing) + retrieval
            + LLM with policy excerpts

Rules are used only to classify short, unambiguous conversational
messages (greetings, thanks, farewells) so they skip the embedding and
vector-search step entirely. Anything ambiguous goes to the RAG path,
whose prompt also allows natural conversational replies as a fallback.
"""
from __future__ import annotations

import re
import unicodedata

CHAT = "chat"
POLICY = "policy"

_MAX_CHAT_LENGTH = 60

_CHAT_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(
        r"^(hi+|hello+|helo+|hey+|heyy+|yo+|greetings|namaste|namaskar|gm|"
        r"good (morning|afternoon|evening|day))( there)?$"
    ),
    re.compile(
        r"^(how (are|r) (you|u)( doing| today)?|how'?s it going|"
        r"what'?s up|whats up|wassup)$"
    ),
    re.compile(r"^(thanks?|thank you|thankyou|thx|ty|tysm|dhanyavaad|shukriya)$"),
    re.compile(r"^(bye+|goodbye|good bye|see you( soon)?|see ya|cya|gn|good night)$"),
    re.compile(r"^(ok+|okay|k|cool|great|nice|fine|good|hmm+|alright|sure)$"),
    re.compile(
        r"^(who are you|what can you do|what do you do|help me|help|"
        r"are you (there|working|alive)|you there|test(ing)?)$"
    ),
)


def normalize(text: str) -> str:
    """Lowercase, unify unicode, strip punctuation, collapse whitespace."""
    text = unicodedata.normalize("NFKC", text or "")
    text = text.lower().replace("\u2019", "'")
    text = re.sub(r"[^a-z0-9'\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def route(question: str) -> str:
    """Classify a message as CHAT (small talk) or POLICY (needs retrieval)."""
    text = normalize(question)
    if not text or len(text) > _MAX_CHAT_LENGTH:
        return POLICY
    for pattern in _CHAT_PATTERNS:
        if pattern.fullmatch(text):
            return CHAT
    return POLICY
